// Generated by Butterfly TypeScript converter
// File: net/HttpMediaType.kt
// Package: com.lightningkite.butterfly.net

//! Declares com.lightningkite.butterfly.net.HttpMediaType
export type HttpMediaType = string;
//! Declares com.lightningkite.butterfly.net.HttpMediaType
export let HttpMediaType = String;

//! Declares com.lightningkite.butterfly.net.HttpMediaTypes
export class HttpMediaTypes {
    public static INSTANCE = new HttpMediaTypes();
    public readonly JSON = "application/json";
    public readonly TEXT = "text/plain";
    public readonly JPEG = "image/jpeg";
    public readonly MULTIPART_FORM_DATA = "multipart/form-data";

}

