// Generated by Butterfly TypeScript converter
// File: net/HttpResponse.kt
// Package: com.lightningkite.butterfly.net

//! Declares com.lightningkite.butterfly.net.HttpResponse
import {parse} from "./jsonParsing";


//! Declares com.lightningkite.butterfly.net.code
export function xResponseCodeGet(this_: Response): number { return this_.status; }

//! Declares com.lightningkite.butterfly.net.headers
export function xResponseHeadersGet(this_: Response): Map<string, string> {
    let map = new Map<string, string>();
    this_.headers.forEach((value, key) => {
        const existing = map.get(key);
        if(existing === undefined){
            map.set(key, value);
        } else {
            map.set(key, existing + ";" + value)
        }
    })
    return map;
}
