// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: observables/CombineManyObservableProperty.kt
// Package: com.lightningkite.butterfly.observables
import { map as rxMap, skip as rxSkip } from 'rxjs/operators'
import { ObservableProperty } from './ObservableProperty'
import { xObservablePropertyMap } from './TransformedObservableProperty'
import { xObservablePropertyObservableGet } from './ObservableProperty.ext'
import { Observable, combineLatest as rxCombineLatest } from 'rxjs'

//! Declares com.lightningkite.butterfly.observables.CombineManyObservableProperty
export class CombineManyObservableProperty<IN> extends ObservableProperty<Array<IN>> {
    public readonly observables: Array<ObservableProperty<IN>>;
    public constructor(observables: Array<ObservableProperty<IN>>) {
        super();
        this.observables = observables;
    }
    
    //! Declares com.lightningkite.butterfly.observables.CombineManyObservableProperty.value
    public get value(): Array<IN> { return this.observables.map((it: ObservableProperty<IN>): IN => it.value); }
    
    //! Declares com.lightningkite.butterfly.observables.CombineManyObservableProperty.onChange
    public get onChange(): Observable<Array<IN>> { return rxCombineLatest(this.observables.map((it: ObservableProperty<IN>): Observable<IN> => xObservablePropertyObservableGet(it))).pipe(rxMap((items: Array<IN>): Array<IN> => items.map((it: IN): IN => it))).pipe(rxSkip(0)); }
    
}

//! Declares com.lightningkite.butterfly.observables.combined>kotlin.collections.List<com.lightningkite.butterfly.observables.ObservableProperty>
export function combinedAndMap<IN, OUT>(this_: Array<ObservableProperty<IN>>, combiner:  ((a: Array<IN>) => OUT)): ObservableProperty<OUT> {
    return xObservablePropertyMap<Array<IN>, OUT>(new CombineManyObservableProperty<IN>(this_), combiner);
}


//! Declares com.lightningkite.butterfly.observables.combined>kotlin.collections.List<com.lightningkite.butterfly.observables.ObservableProperty>
export function xListCombined<T>(this_: Array<ObservableProperty<T>>): ObservableProperty<Array<T>> {
    return new CombineManyObservableProperty<T>(this_);
}

