// Generated by Butterfly TypeScript converter - this file will be overwritten.
// File: observables/Event.kt
// Package: com.lightningkite.butterfly.observables
import { Observer } from 'rxjs'

//! Declares com.lightningkite.butterfly.observables.invokeAll>io.reactivex.Observer<kotlin.Any>
export function xObserverInvokeAll<Element>(this_: Observer<Element>, value: Element): void { 
    return this_.next(value); 
}

