// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: observables/ObservableProperty.ext.kt
// Package: com.lightningkite.butterfly.observables
import { Observable, Observer, SubscriptionLike, concat as rxConcat } from 'rxjs'
import { printStackTrace } from '../kotlin/Language'
import { ObservableProperty } from './ObservableProperty'
import { xObservablePropertyMap } from './TransformedObservableProperty'
import { MutableObservableProperty } from './MutableObservableProperty'
import { EqualOverrideSet } from '../KotlinCollections'
import { map as rxMap } from 'rxjs/operators'
import { xObservablePropertyWithWrite } from './WriteAddedObservableProperty'

//! Declares com.lightningkite.butterfly.observables.observable>com.lightningkite.butterfly.observables.ObservableProperty<kotlin.Any>
export function xObservablePropertyObservableGet<T>(this_: ObservableProperty<T>): Observable<T> { return rxConcat(new Observable((it: Observer<T>): void => {
                it.next(this_.value); it.complete();
}), this_.onChange); }

//! Declares com.lightningkite.butterfly.observables.observableNN>com.lightningkite.butterfly.observables.ObservableProperty<kotlin.Any>
export function xObservablePropertyObservableNNGet<T>(this_: ObservableProperty<T>): Observable<T> { return rxConcat(new Observable((it: Observer<T>): void => {
                it.next(this_.value); it.complete();
}), this_.onChange).pipe(rxMap((it: T): T => it)); }

//! Declares com.lightningkite.butterfly.observables.onChangeNN>com.lightningkite.butterfly.observables.ObservableProperty<kotlin.Any>
export function xObservablePropertyOnChangeNNGet<T>(this_: ObservableProperty<T>): Observable<T> { return this_.onChange.pipe(rxMap((it: T): T => it)); }


//! Declares com.lightningkite.butterfly.observables.subscribeBy>com.lightningkite.butterfly.observables.ObservableProperty<kotlin.Any>
export function xObservablePropertySubscribeBy<T>(this_: ObservableProperty<T>, onError:  ((a: any) => void) = (it: any): void => {
        printStackTrace(it);
}, onComplete:  (() => void) = (): void => {}, onNext:  ((a: T) => void) = (it: T): void => {}): SubscriptionLike { 
    return xObservablePropertyObservableGet(this_).subscribe((boxed: T): void => {
            onNext(boxed);
    }, onError, onComplete); 
}

//! Declares com.lightningkite.butterfly.observables.includes
export function includes<E>(collection: MutableObservableProperty<Set<E>>, element: E): MutableObservableProperty<boolean> {
    return xObservablePropertyWithWrite<boolean>(xObservablePropertyMap<Set<E>, boolean>(collection, (it: Set<E>): boolean => it.has(element)), (it: boolean): void => {
            if (it) {
                collection.value = new EqualOverrideSet([...collection.value, element]);
            } else {
                collection.value = new EqualOverrideSet([...collection.value].filter(x => x !== element));
            }
    });
}

//! Declares com.lightningkite.butterfly.observables.whileActive>com.lightningkite.butterfly.observables.ObservableProperty<kotlin.Boolean>
export function xObservablePropertyWhileActive(this_: ObservableProperty<boolean>, action:  (() => SubscriptionLike)): SubscriptionLike {
    let current: (SubscriptionLike | null) = null;
    
    return xObservablePropertySubscribeBy<boolean>(this_, undefined, undefined, (it: boolean): void => {
            if (it) {
                if (current === null) {
                    current = action();
                }
            } else {
                const temp65 = current;
                if(temp65 !== null) { 
                    temp65.unsubscribe()
                };
                current = null;
            }
    });
}
