// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: observables/ReferenceObservableProperty.kt
// Package: com.lightningkite.butterfly.observables
import { MutableObservableProperty } from './MutableObservableProperty'
import { Observable } from 'rxjs'

//! Declares com.lightningkite.butterfly.observables.ReferenceObservableProperty
export class ReferenceObservableProperty<T> extends MutableObservableProperty<T> {
    public readonly get:  (() => T);
    public readonly set:  ((a: T) => void);
    public readonly event: Observable<T>;
    public constructor(get:  (() => T), set:  ((a: T) => void), event: Observable<T>) {
        super();
        this.get = get;
        this.set = set;
        this.event = event;
    }
    
    
    //! Declares com.lightningkite.butterfly.observables.ReferenceObservableProperty.onChange
    public get onChange(): Observable<T> { return this.event; }
    
    //! Declares com.lightningkite.butterfly.observables.ReferenceObservableProperty.value
    public get value(): T { return this.get(); }
    public set value(value: T) {
        this.set(value);
    }
    
    public update(): void {
        //do nothing
    }
}

