// Generated by Butterfly TypeScript converter - this file will be overwritten.
// File: observables/StandardObservableProperty.shared.kt
// Package: com.lightningkite.butterfly.observables
import { MutableObservableProperty } from './MutableObservableProperty.shared'
import { Subject } from 'rxjs'

//! Declares com.lightningkite.butterfly.observables.StandardObservableProperty
export class StandardObservableProperty<T> extends MutableObservableProperty<T> {
    public underlyingValue: T;
    public readonly onChange: Subject<T>;
    public constructor(underlyingValue: T, onChange: Subject<T> = new Subject()) {
        super();
        this.underlyingValue = underlyingValue;
        this.onChange = onChange;
    }
    
    //! Declares com.lightningkite.butterfly.observables.StandardObservableProperty.value
    public get value(): T { return this.underlyingValue; }
    public set value(value: T) {
        this.underlyingValue = value;
        this.onChange.next(value);
    }
    
    
    public update(): void {
        this.onChange.next(this.value);
    }
}

