// Generated by Butterfly TypeScript converter
// File: location/Geocoding.kt
// Package: com.lightningkite.butterfly.location
import { GeoCoordinate } from './GeoCoordinate'
import { GeoAddress } from './GeoAddress'
import { post } from '../delay'
import {Observable, of} from "rxjs";

let geoMethod = (
    this_Geocode: Window,
    coordinate: GeoCoordinate | string,
    maxResults: number = 1
): Observable<Array<GeoAddress>> => of([])
export function setGeocodingMethod(method: (
    this_Geocode: Window,
    coordinate: GeoCoordinate | string,
    maxResults: number
)=>Observable<Array<GeoAddress>>) {
    geoMethod = method
}

//! Declares com.lightningkite.butterfly.location.geocode
export function xActivityAccessGeocode(
    this_Geocode: Window,
    coordinate: GeoCoordinate | string,
    maxResults: number = 1
): Observable<Array<GeoAddress>> {
    return geoMethod(this_Geocode, coordinate)
}

