// Generated by Butterfly TypeScript converter - this file will be overwritten.
// File: time/DateAlone.shared.kt
// Package: com.lightningkite.butterfly.time
import { TimeAlone } from './TimeAlone.actual'
import { dateFrom, xDateFormat } from './Date.actual'
import { DateAlone } from './DateAlone.actual'
import { ClockPartSize } from './ClockPartSize.shared'

//! Declares com.lightningkite.butterfly.time.set>com.lightningkite.butterfly.time.DateAlone
export function xDateAloneSet(this_: DateAlone, other: DateAlone): DateAlone {
    this_.year = other.year;
    this_.month = other.month;
    this_.day = other.day;
    return this_;
}

//! Declares com.lightningkite.butterfly.time.format>com.lightningkite.butterfly.time.DateAlone
export function xDateAloneFormat(this_: DateAlone, clockPartSize: ClockPartSize): string { 
    return xDateFormat(dateFrom(this_, TimeAlone.Companion.INSTANCE.noon, undefined), clockPartSize, ClockPartSize.None); 
}

