// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: time/TimeAlone.ext.kt
// Package: com.lightningkite.butterfly.time
import { xIntFloorDiv, xIntFloorMod } from '../floorMod'
import { TimeAlone } from './TimeAlone'
import { dateFrom, xDateDateAloneGet, xDateFormat } from './Date'
import { ClockPartSize } from './ClockPartSize'

//! Declares com.lightningkite.butterfly.time.normalize>com.lightningkite.butterfly.time.TimeAlone
export function xTimeAloneNormalize(this_: TimeAlone): void {
    this_.hour = xIntFloorMod((this_.hour + xIntFloorDiv(this_.minute, 60)), 24);
    this_.minute = xIntFloorMod((this_.minute + xIntFloorDiv(this_.second, 60)), 60);
    this_.second = xIntFloorMod(this_.second, 60);
}

//! Declares com.lightningkite.butterfly.time.set>com.lightningkite.butterfly.time.TimeAlone
export function xTimeAloneSet(this_: TimeAlone, other: TimeAlone): TimeAlone {
    this_.hour = other.hour;
    this_.minute = other.minute;
    this_.second = other.second;
    return this_;
}


//! Declares com.lightningkite.butterfly.time.format>com.lightningkite.butterfly.time.TimeAlone
export function xTimeAloneFormat(this_: TimeAlone, clockPartSize: ClockPartSize): string { 
    return xDateFormat(dateFrom(xDateDateAloneGet(new Date()), this_, undefined), ClockPartSize.None, clockPartSize); 
}

