// Generated by Butterfly TypeScript converter
// File: rx/DisposeCondition.actual.kt
// Package: com.lightningkite.butterfly.rx
import { DisposeCondition } from './DisposeCondition.shared'
import { SubscriptionLike } from 'rxjs'
import {addDetatchEvent} from "../views/viewAttached";

//! Declares com.lightningkite.butterfly.rx.removed
export function xViewRemovedGet(this_Removed: HTMLElement): DisposeCondition {
    return new DisposeCondition((a)=>{
        addDetatchEvent(this_Removed, (_)=>{
            a.unsubscribe();
        })
    })
}


//! Declares com.lightningkite.butterfly.rx.DisposableLambda
export class DisposableLambda implements SubscriptionLike {
    closed: boolean = false;
    lambda: ()=>void;
    constructor(lambda: ()=>void) {
        this.lambda = lambda
    }

    unsubscribe(): void {
        if(this.closed) { return }
        this.closed = true;
        this.lambda();
    }

}


//! Declares com.lightningkite.butterfly.rx.forever
export function xDisposableForever<Self extends SubscriptionLike>(this_Forever: Self): Self{
    return this_Forever;
}

//! Declares com.lightningkite.butterfly.rx.until
export function xDisposableUntil<Self extends SubscriptionLike>(this_Until: Self, condition: DisposeCondition): Self{
    condition.call(this_Until);
    return this_Until;
}

