// Generated by Butterfly TypeScript converter
// File: rx/RxExtensions.kt
// Package: com.lightningkite.butterfly.rx
import {finalize as rxFinalize, map as rxMap, filter as rxFilter, filter} from 'rxjs/operators'
import { MutableObservableProperty } from '../observables/MutableObservableProperty'
import { doOnSubscribe } from '../Kotlin'
import { Observable} from 'rxjs'
import { post } from '../delay'
import {MonoTypeOperatorFunction} from "rxjs/internal/types";
//! Declares com.lightningkite.butterfly.rx.working
export function xSingleWorking<Element extends any>(this_Working: Observable<Element>, observable: MutableObservableProperty<Boolean>): Observable<Element>{
    return rxFinalize(() => post(() => observable.value = false))(doOnSubscribe(this_Working, (it) => post(() => observable.value = true))) as Observable<Element>;
}

//! Declares com.lightningkite.butterfly.rx.mapNotNull
export function xObservableMapNotNull<A, B>(this_: Observable<A>, transform: (a: A)=>(B | null)): Observable<B> {
    return this_.pipe(
        rxMap(transform),
        rxFilter((a)=> a !== null && a !== undefined)
    ) as Observable<B>
}

//! Declares com.lightningkite.butterfly.rx.filterNotNull
export function xObservableFilterNotNull<T>(this_: Observable<T | null>): Observable<T> {
    return this_.pipe(
        filter(x => x !== null && x !== undefined)
    ) as Observable<T>
}