// Generated by Butterfly TypeScript converter - this file will be overwritten.
// File: views/EmptyView.kt
// Package: com.lightningkite.butterfly.views

//! Declares com.lightningkite.butterfly.views.newEmptyView
export function newEmptyView(dependency: Window): HTMLElement { 
    return document.createElement('div'); 
}

