// Generated by Butterfly TypeScript converter - this file will be overwritten.
// File: views/HasBackAction.shared.kt
// Package: com.lightningkite.butterfly.views

//! Declares com.lightningkite.butterfly.views.HasBackAction
export interface HasBackAction {
    
    onBackPressed(): boolean 
}
export namespace HasBackActionDefaults {
    export function onBackPressed(this_: HasBackAction): boolean { 
        return false; 
    }
}
