// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: views/ImageView.loadVideoThumbnail.kt
// Package: com.lightningkite.butterfly.views
import { Image } from '../Image'
import { xDisposableForever } from '../rx/DisposeCondition.ext'
import { xImageViewLoadImage } from './ImageView'
import { Video } from '../Video'
import { SubscriptionLike } from 'rxjs'
import { xVideoThumbnail } from '../Video.ext'

//! Declares com.lightningkite.butterfly.views.loadVideoThumbnail>android.widget.ImageView
export function xImageViewLoadVideoThumbnail(this_: HTMLImageElement, video: (Video | null)): void {
    if (video === null) { return }
    xImageViewLoadImage(this_, null);
    xDisposableForever<SubscriptionLike>(xVideoThumbnail(video!, undefined, undefined).subscribe((it: Image): void => {
                xImageViewLoadImage(this_, it);
            }, (it: any): void => {
                xImageViewLoadImage(this_, null);
    }));
}
