// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: views/showDialog.kt
// Package: com.lightningkite.butterfly.views
import { ViewString } from './ViewString'
import { StandardObservableProperty } from '../observables/StandardObservableProperty'
import { Subject } from 'rxjs'

//! Declares com.lightningkite.butterfly.views.lastDialog
export const _lastDialog = new StandardObservableProperty<(DialogRequest | null)>(null, undefined);
export function getLastDialog(): StandardObservableProperty<(DialogRequest | null)> { return _lastDialog; }

//! Declares com.lightningkite.butterfly.views.showDialogEvent
export const _showDialogEvent: Subject<DialogRequest> = new Subject();
export function getShowDialogEvent(): Subject<DialogRequest> { return _showDialogEvent; }


//! Declares com.lightningkite.butterfly.views.DialogRequest
export class DialogRequest {
    public readonly _string: ViewString;
    public readonly confirmation: ((() => void) | null);
    public constructor(_string: ViewString, confirmation: ((() => void) | null) = null) {
        this._string = _string;
        this.confirmation = confirmation;
    }
}

//! Declares com.lightningkite.butterfly.views.showDialog
export function showDialog(request: DialogRequest): void {
    getLastDialog().value = request;
    getShowDialogEvent().next(request);
}

//! Declares com.lightningkite.butterfly.views.showDialog
export function showDialogAlert(message: ViewString): void {
    showDialog(new DialogRequest(message, undefined));
}

