// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: views/ViewGenerator.kt
// Package: com.lightningkite.butterfly.views
import { newEmptyView } from './EmptyView'
import { ViewString, ViewStringRaw } from './ViewString'

//! Declares com.lightningkite.butterfly.views.ViewGenerator
export abstract class ViewGenerator {
    protected constructor() {
    }
    
    //! Declares com.lightningkite.butterfly.views.ViewGenerator.title
    public get title(): string { return ""; }
    
    //! Declares com.lightningkite.butterfly.views.ViewGenerator.titleString
    public get titleString(): ViewString { return new ViewStringRaw(this.title); }
    
    
    public abstract generate(dependency: Window): HTMLElement 
    
    
}
export namespace ViewGenerator {
    //! Declares com.lightningkite.butterfly.views.ViewGenerator.Default
    export class Default extends ViewGenerator {
        public constructor() {
            super();
        }
        
        public generate(dependency: Window): HTMLElement { 
            return newEmptyView(dependency); 
        }
    }
}

