// Generated by Butterfly TypeScript converter
// File: observables/binding/Button.binding.kt
// Package: com.lightningkite.butterfly.observables.binding
import { xViewRemovedGet, xDisposableUntil } from '../../rx/DisposeCondition.ext'
import { ObservableProperty } from '../ObservableProperty'
import {xObservablePropertySubscribeBy} from "../ObservableProperty.ext";

//! Declares com.lightningkite.butterfly.observables.binding.bindActive>android.widget.Button
export function xButtonBindActive(this_: HTMLButtonElement, observable: ObservableProperty<boolean>, activeColorResource: (string | null) = null, inactiveColorResource: (string | null) = null): void {
    xDisposableUntil(xObservablePropertySubscribeBy(observable, undefined, undefined, (x) => {
        this_.disabled = !x;
    }), xViewRemovedGet(this_));
}
