// Generated by Butterfly TypeScript converter
// File: observables/binding/EditText.binding.kt
// Package: com.lightningkite.butterfly.observables.binding
import {xObservablePropertySubscribeBy} from '../ObservableProperty.ext'
import {parseFloatOrNull, parseIntOrNull, takeUnless} from '../../Kotlin'
import {
    xViewRemovedGet,
    xDisposableUntil
} from '../../rx/DisposeCondition.ext'
import {MutableObservableProperty} from '../MutableObservableProperty'

//! Declares com.lightningkite.butterfly.observables.binding.bindString>android.widget.EditText
export function xEditTextBindString(this_: HTMLInputElement | HTMLTextAreaElement, observable: MutableObservableProperty<string>): void {
    xDisposableUntil(xObservablePropertySubscribeBy(observable, undefined, undefined, (value) => {
        if (observable.value !== this_.value.toString()) {
            this_.value = observable.value;
        }
    }), xViewRemovedGet(this_));
    this_.oninput = (e) => {
        const s = this_.value;
        if (observable.value !== s) {
            observable.value = s;
        }
    }
}

//! Declares com.lightningkite.butterfly.observables.binding.bindInteger>android.widget.EditText
export function xEditTextBindInteger(this_: HTMLInputElement | HTMLTextAreaElement, observable: MutableObservableProperty<number>): void {
    xDisposableUntil(xObservablePropertySubscribeBy(observable, undefined, undefined, (value) => {
        const currentValue = parseIntOrNull(this_.value);

        if (value !== currentValue) {
            this_.value = takeUnless(value, (it) => it === 0)?.toString() ?? "";
        }
    }), xViewRemovedGet(this_));
    this_.oninput = (e) => {
        const currentValue = parseIntOrNull(this_.value) ?? 0;

        if (observable.value !== currentValue) {
            observable.value = currentValue;
        }
    }
}


//! Declares com.lightningkite.butterfly.observables.binding.bindDouble>android.widget.EditText
export function xEditTextBindDouble(this_: HTMLInputElement | HTMLTextAreaElement, observable: MutableObservableProperty<number>): void {
    xDisposableUntil(xObservablePropertySubscribeBy(observable, undefined, undefined, (value) => {
        const currentValue = parseFloatOrNull(this_.value);

        if (value !== currentValue) {
            this_.value = takeUnless(value, (it) => it === 0.0)?.toString() ?? "";
        }
    }), xViewRemovedGet(this_));
    this_.oninput = (e) => {
        const currentValue = parseFloatOrNull(this_.value) ?? 0;

        if (observable.value !== currentValue) {
            observable.value = currentValue;
        }
    }
}

