// Generated by Butterfly TypeScript converter - this file will be overwritten.
// File: observables/binding/View.binding.kt
// Package: com.lightningkite.butterfly.observables.binding
import { xDisposableUntil, xViewRemovedGet } from '../../rx/DisposeCondition.ext'
import { ObservableProperty } from '../ObservableProperty'
import { xObservablePropertySubscribeBy } from '../ObservableProperty.ext'
import { setViewVisibility } from '../../views/View.ext'
import { SubscriptionLike } from 'rxjs'

//! Declares com.lightningkite.butterfly.observables.binding.bindVisible>android.view.View
export function xViewBindVisible(this_: HTMLElement, observable: ObservableProperty<boolean>): void {
    xDisposableUntil<SubscriptionLike>(xObservablePropertySubscribeBy<boolean>(observable, undefined, undefined, (value: boolean): void => {
                setViewVisibility(this_, value ? "visible" : "invisible");
    }), xViewRemovedGet(this_));
}


//! Declares com.lightningkite.butterfly.observables.binding.bindExists>android.view.View
export function xViewBindExists(this_: HTMLElement, observable: ObservableProperty<boolean>): void {
    xDisposableUntil<SubscriptionLike>(xObservablePropertySubscribeBy<boolean>(observable, undefined, undefined, (value: boolean): void => {
                setViewVisibility(this_, value ? "visible" : "gone");
    }), xViewRemovedGet(this_));
}

