// Generated by Butterfly TypeScript converter
// File: views/draw/LinearGradient.kt
// Package: com.lightningkite.butterfly.views.draw

//! Declares com.lightningkite.butterfly.views.draw.newRadialGradient
import {CanvasGradientMaker, Shader} from "./LinearGradient";

export function newRadialGradient(
    centerX: number,
    centerY: number,
    radius: number,
    colors: Array<string>,
    positions: Array<number>,
    tile: Shader.TileMode
): CanvasGradientMaker {
    return (ctx) => {
        let g = ctx.createRadialGradient(centerX, centerY, 0, centerX, centerY, radius);
        for(let i = 0; i < colors.length; i++){
            g.addColorStop(positions[i], colors[i]);
        }
        return g;
    }
}
