// Generated by Butterfly TypeScript converter - this file will be overwritten.
// File: Failable.shared.kt
// Package: com.lightningkite.butterfly

//! Declares com.lightningkite.butterfly.Failable
export class Failable<T> {
    public readonly result: (T | null);
    public readonly issue: (string | null);
    public constructor(result: (T | null) = null, issue: (string | null) = null) {
        this.result = result;
        this.issue = issue;
    }
    
    
}
export namespace Failable {
    //! Declares com.lightningkite.butterfly.Failable.Companion
    export class Companion {
        private constructor() {
        }
        public static INSTANCE = new Companion();
        
        public failure<T>(message: string): Failable<T> { return new Failable<T>(undefined, message); }
        public success<T>(value: T): Failable<T> { return new Failable<T>(value, undefined); }
    }
}

