// Generated by Butterfly TypeScript converter
// File: Preferences.kt
// Package: com.lightningkite.butterfly
import { IsCodable, xAnyToJsonString, xStringFromJsonString } from './Codable'

//! Declares com.lightningkite.butterfly.Preferences
export class Preferences {
    private constructor() {
    }
    public static INSTANCE = new Preferences();

    set<T>(T: any, key: string, value: T): void{
        window.localStorage.setItem(key, xAnyToJsonString(value))
    }
    
    remove(key: string): void{
        window.localStorage.removeItem(key)
    }
    
    get<T extends IsCodable>(T: any, key: string): (T | null){
        const thing = window.localStorage.getItem(key);
        if(thing === null || thing === undefined) return null;
        try {
            return xStringFromJsonString(thing, T);
        } catch(e) {
            return null;
        }
    }
    
    clear(): void{
        window.localStorage.clear();
    }
}

