// Generated by Butterfly TypeScript converter
// File: Random.actual.kt
// Package: com.lightningkite.butterfly

import MersenneTwister from "mersenne-twister";

const RandomInstance = new MersenneTwister();
export { RandomInstance }