// Generated by Butterfly TypeScript converter
// File: SecurePreferences.kt
// Package: com.lightningkite.butterfly
import { IsCodable, xAnyToJsonString, xStringFromJsonString } from './Codable'
import {Preferences} from "./Preferences";

//! Declares com.lightningkite.butterfly.SecurePreferences
export class SecurePreferences {
    private constructor() {
    }
    public static INSTANCE = Preferences.INSTANCE;

}

