// Generated by Butterfly TypeScript converter
// File: SecurePreferences.actual.kt
// Package: com.lightningkite.butterfly
import { IsCodable, xAnyToJsonString, xStringFromJsonString } from './Codable.actual'
import {Preferences} from "./Preferences.actual";

//! Declares com.lightningkite.butterfly.SecurePreferences
export class SecurePreferences {
    private constructor() {
    }
    public static INSTANCE = Preferences.INSTANCE;

}

